// Generated by `node tools/import-content.mjs` from local material in opt/.
const episodes = [
  {
    "id": "asleep",
    "volume": "vol.8",
    "category": "radio",
    "publishedAt": "2026-08-11",
    "zh": {
      "title": "20241115 - asleep",
      "heading": "「即兴演奏」",
      "body": [
        "！？一周年？！\n已经。。一年了么。。时间过的比想象中的还要快\n这一期其实是24年下半年为1229冷空气演出准备憋原创的时候，拿中东新活录音房里那台p125当midi键盘即兴弹出来的东西，然后后面修了一些节奏，最近把结尾改了补了俩小节弦乐，换了个吉他的音源。所谓「键吉」，就是用midi弹吉他音色，其实有一种“演都不演了”的独特质感，也算是前个阶段写东西的癖好了。\nasleep 其实很早就想要端出来了，因为大概算是我有意识地记录这种「长即兴」的最早的尝试，比这个日期更早的内容可能就太不成熟了。而我个人非常非常喜欢这次的内容。",
        "我其实在想，专门挑在一周年的时候，发期电台然后写点什么，到底是不是有必要的，我会这样反问我自己。因为好像也没有什么可总结的，没啥特别的企划，也办不到连续地更新，至于发电台这件事本身于我的心路历程，前面的节目里也分多轮次，多主题，多角度，壁画连篇地提到过很多次。我其实会很希望做到连续更新，或毋宁说，我希望这个播客，或者说电台，对听的人来说来说是一种陪伴。我能够回想起听到某一段的时候，我在哪里散步，眼前有怎样的风景，那时的我在为什么而烦恼，如果音频能够与这些记忆锚定关联起来，他们同时都会变得鲜活而易于检索，从而尽量放慢一些对时间的感知。",
        "「人对时间的感知能力取决于这段时间在人生中的占比，对当时的你来说义务教育的九年几乎就是你人生的全部了，而上大学后的十年只占你人生的三分之一」",
        "人生总会出现各种相遇 但实际这些相遇 无论是学习工作的机会 生活的境遇 与人的相遇，或是 开一本新书、决心打通某个游戏、听到喜欢的曲子 想要去扒和练和模仿着写的念头，都是可以数清的 非常有限的机遇。但是，年轻的人依旧会默认自己是“永生”的，在潜意识里，我还有无穷的时间 去做我想做的各种事情，我还有未读的书单，还有机会通关更多大作，我还有要练的曲子，还有一大批等着改进的demo作品；而可预见的是，在将来的某一个随机而凉爽的夏夜，满月升起，它数十亿年以来冷静而原样地存在，完成月相的更迭，而此刻正好被某个散步的中登看到。“我还能多少次看到满月升起？”，“大概二十次”。",
        "越是意识到时间流逝，越是意识到终将死去，越是意识到人对死亡到来时间的无知 人在时间的推进中 就越是会逐渐将自己会永生 或者说 “yet it all seems limitless” 这样的念头 从潜意识里祓除。“终有一天 我会清晰的认识到这些可以数的清的次数”这件事其实算是死亡的二阶导数，等待他的来临和等待死亡的来临没有本质区别。因此除了等待，其实还有相当多的工作要做，相当多的步子要迈，相当多的电台要发，相当多的个人项目要做。。。存在主义有其稳定的SOP。",
        "过去的一年，你台发了7期节目，在上个月播放也过了一千，我其实相当惊讶，因为的确我没有广泛传播这些粗糙的即兴音乐的想法，将其限制在私域里已是目前的我能够迈出的最大的勇气，而事实上，这些东西真的有人愿意点开去听，忍受其中 频繁的掉拍，模糊的听感，偏移的调律，在其中尝试捕捉哪些隐藏在瑕疵中的值得一听的voicing，和声切换，动态，即兴的曲式编排。。。与隐藏在这些小节中的我的表达。对我来说，这就是迈出这一步的全部的意义。",
        "最近没有琴弹，电台节目以及一些创作都非常难产，所以开始发一些在香港录的弹琴视频的存货，事实上，所有的创作和即兴都需要基于长时间的积累，而积累源自于听曲和练琴，好在目前听和练的念头还是相当频繁的，等下半年逐渐settle了就买琴，决不能让这些念头频繁地落空。"
      ],
      "date": "2026.08.11",
      "note": "vol.8 / 即兴演奏"
    },
    "en": {
      "title": "20241115 - asleep",
      "heading": "“Improvisation”",
      "body": [
        "What?! The first anniversary?! Has it really been a year already? Time has moved faster than I imagined. I first improvised this in the second half of 2024, while trying to force out original material for Cold Air’s 29 December show. I used the P-125 in Zhongdong Xinhui’s recording room as a MIDI keyboard, fixed some of the rhythm afterwards, and recently rewrote the ending, added two bars of strings, and replaced the guitar patch. By “keyboard guitar,” I mean playing a guitar sound through MIDI. It has a distinctive quality of not even pretending to be the real thing, and was one of my favourite habits in that phase of writing. I had wanted to put “asleep” out for a long time. It may be my earliest conscious attempt to preserve one of these long improvisations; anything earlier is probably too immature. I personally love this recording very, very much.",
        "I have been asking myself whether it is necessary to choose the anniversary deliberately, release an episode, and write something for the occasion. There does not seem to be much to summarise. There was no special project, and I never managed to update continuously. As for the inner history of releasing this radio, earlier episodes have already approached it over and over, through different themes and from different angles, in walls of text. I would like to update steadily—or rather, I want this podcast, this radio, to become a kind of company for whoever listens. I can remember where I was walking when I heard a certain passage, what the landscape looked like, and what troubled me then. When audio becomes anchored to those memories, both the sound and the memory become vivid and easy to retrieve, slowing the feeling of time as much as possible.",
        "“A person’s sense of time depends on the share of their life that a period occupies. For you as a child, the nine years of compulsory education were almost your entire life; the ten years after university occupy only a third of it.”",
        "Life keeps producing encounters, but every one of them—the chance to study or work, a circumstance, another person, opening a new book, deciding to finish a game, hearing a piece and wanting to transcribe, practise, imitate, or write—is countable. They are severely limited opportunities. Yet young people still assume they are immortal. Somewhere beneath consciousness, I still have unlimited time to do everything I want. There are unread books, more major games to finish, pieces to practise, and a whole batch of demos waiting to be improved. But one foreseeable night in some future summer, cool and otherwise random, a full moon will rise. It will complete another phase, existing calmly and unchanged as it has for billions of years, and happen to be seen by some middle-aged person out for a walk. “How many more times will I see the full moon rise?” “Perhaps twenty.”",
        "The more clearly one sees time passing, the certainty of death, and our ignorance of when it will arrive, the more the progress of time exorcises the unconscious thought that one is immortal—that “yet it all seems limitless.” The day on which I clearly recognise that the remaining occasions can be counted is, in a sense, the second derivative of death. Waiting for that day and waiting for death are not essentially different. So there is plenty to do besides wait: many steps to take, many episodes to release, many personal projects to make. Existentialism has a dependable SOP.",
        "Over the past year this little station released seven episodes, and last month its plays passed one thousand. I was honestly astonished. I never intended to circulate these rough improvisations widely; keeping them within a private circle was already the largest act of courage I could manage. Yet people really did choose to open them and listen—to tolerate the frequent lost beats, muddy sound, drifting tuning, and to look inside those flaws for voicings, harmonic turns, dynamics, and improvised structures worth hearing, along with whatever I was trying to express between the bars. For me, that is the entire meaning of taking this step.",
        "I have not had a piano to play lately, so both the radio and other creative work have been painfully slow. I started posting some of the piano videos I recorded in Hong Kong instead. Every work and improvisation depends on long accumulation, and that accumulation comes from listening and practising. Fortunately, the urge to do both is still frequent. Once life settles a little in the second half of the year, I will buy a piano. I cannot keep letting those impulses come to nothing."
      ],
      "date": "11 Aug 2026",
      "note": "vol.8 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/asleep/01.jpg",
        "caption": "cover"
      },
      {
        "src": "assets/content/radio/asleep/02.jpg",
        "caption": "马蹄山村"
      },
      {
        "src": "assets/content/radio/asleep/03.jpg",
        "caption": "沅江2"
      },
      {
        "src": "assets/content/radio/asleep/04.jpg",
        "caption": "中东新活1"
      }
    ],
    "cover": "assets/content/radio/asleep/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20241115%20-%20asleep.mp3",
    "durationSeconds": 329,
    "durationLabel": "05:29",
    "sizeBytes": 6592700,
    "sizeLabel": "6.3 MB",
    "bitrateKbps": 160,
    "tags": {}
  },
  {
    "id": "sazanami",
    "volume": "vol.7",
    "category": "radio",
    "publishedAt": "2026-05-18",
    "zh": {
      "title": "20260125 - Sazanami",
      "heading": "「即兴演奏」",
      "body": [
        "这一期是年前的存货，和声选择方面其实和上一期有些相同的语彙搭配，但是选择了相当不同的切换 编排和织体。说是织体，倒不如说是手癖，（甚至说是笔者手癖精华都不为过x，总之是很简单的织体了，演奏量少是很客观的，织体想象力太过受限，而且一旦偏离手癖开始尝试其他排列又会不可避免的掉拍或者出现不好的听感，尤其在高bpm的情况下。当然当时弹的时候没想这么多，自己先爽了再说。。咳，织体确实是一个非常非常大的进化方向了。",
        "开头的这种杂谈往往会简单介绍一下曲子的基本情况，然后很随意的讲一些音乐的想法，生活的近况等等，参考了播客《基本无害》的结构；往往到了后面的长篇壁画，才能让我心里那个“暴露狂”被满足，这也是种基本无害的行为。我平时的确会有意无意写一些东西，在备忘录和手记里，不过自从好像是上上个月手记app出bug闪退删掉了我还在编辑中的超长一大段文字之后，感觉被cz，就一直养胃了，停笔断更到现在，不过想想或许断更才是一种更健康的现象吧。总之这并不属于所谓日记类的东西，电台中的部分内容会部分取材参考自这里，不过并不是全部，积压的思想总要释放，不能老憋着幻想着有一天会有一个或是“自然”或是“盆景”的与他人深度沟通的场合，那就太压抑了。。",
        "幻想某天，长篇大论的想法会在“自然”中向某人诉说，或者在私域甚至公域的“盆景”里发表出来，基于这种念头，“暴露癖”才能被暂时性的满足，从而能够办到在现实生活的真正的社交中实现绝对的对自我暴露的控制，这样以后，当下的情绪与感受沉淀下来，形成文字或别的什么实体，原理大概就是像这样吧。这种念头不是平白无故产生的，当焦虑与不安全感太强，人会倾向于通过“暴露”思想来减轻内在的压力，而这并不是真正的表达欲，区分他们是很有必要的事情。电台里写的东西需要是更偏向表达欲的那部分，即便可能没有任何文学性，趣味性，或者普适性，但起码他们是我过了脑子的东西，是通过理智将情绪转化为意识体验的手段，就和这些音乐一样。",
        "这件事能且仅能在度过某一段负面情绪之后做，或者说在埋头奔走的空档中进行，这也是你台名字「合間」的由来了。",
        "这其实是我们所生活的现实的非现成性的体现。引用下上期的一句「身处逆境中心的人是不会真的把逆境当作生活的幸存者偏差的，身处顺境的人同样。」 （我其实还挺喜欢这句的x，文明的脆弱性只有在文明毁灭之后才能真正体现出来，人的脆弱性只有在人死亡之后才能体现出来，感情的脆弱性只有在关系断裂之后才能体现出来。好像的确只有在前置结束后的间隔中，才能体会到更接近真实的世界和自己。",
        "突然又回想起了高中在雅礼的日子，那是纯粹的表达欲极大地盖过没落情绪的日子，是随时随地都能生发出真正属于“自然”的深度沟通的日子，也是我世界观拓荒的日子。或许长大以后更多的思想并不需要太多他人的眼睛观测。或许不是。不过可预见的是，属于“自然”的日子正在逐渐过去，你我都需要学着拥抱“盆景”。"
      ],
      "date": "2026.05.18",
      "note": "vol.7 / 即兴演奏"
    },
    "en": {
      "title": "20260125 - Sazanami",
      "heading": "“Improvisation”",
      "body": [
        "This episode is something left from before the new year. The harmonic choices share some vocabulary with the previous episode, but the switching, arrangement, and texture are quite different.",
        "Calling it texture may be too generous. It is closer to a set of habits in the hands. The amount of playing is objectively sparse, and the imagination of the texture is limited. Once I move away from those habits and try another pattern, the beat can slip or the feel turns bad, especially at a higher BPM. I was not thinking that much while playing. I just enjoyed it first. Still, texture is clearly one of the biggest directions for growth.",
        "The opening talk usually introduces the basic state of the piece, then drifts into music, recent life, and other loose thoughts. I borrowed that structure from the podcast Basic Harmless. The longer wall of text later is where the part of me that wants to expose itself gets temporarily satisfied. That, too, is a basically harmless behavior.",
        "I do write things from time to time in notes and journals. But after a journaling app crashed and deleted a very long paragraph I was still editing, I stopped writing for a while. Maybe stopping is healthier. In any case, this is not exactly a diary. Parts of the radio text may come from there, but not all of it. Accumulated thought needs somewhere to go. It is too suffocating to keep imagining that one day there will be a natural or cultivated occasion for deep communication with another person.",
        "Maybe long thoughts will one day be spoken naturally to someone, or published inside some private or public bonsai-like space. That fantasy lets the impulse to expose myself calm down for a while, so in actual social life I can keep control over how much of myself is revealed.",
        "When the feeling of the present settles and becomes text, music, or another object, the mechanism is probably something like this. Anxiety and insecurity can push a person to expose thought in order to release inner pressure. That is not the same as a real desire to express. Distinguishing the two matters.",
        "The text in the radio should come closer to expression. It may not be literary, interesting, or universal, but at least it has passed through thought. It is a way of turning emotion into conscious experience through reason, just like the music.",
        "This can only happen after a stretch of negative emotion has passed, or during a gap in the middle of running around. That is also where the name Aima comes from.",
        "Maybe this is a sign of the non-readymade nature of the reality we live in. To quote a line from the previous episode: people at the center of adversity do not truly treat adversity as survivorship bias, and neither do people in favorable circumstances. I still like that sentence. The fragility of civilization only truly appears after civilization collapses; the fragility of a person only after death; the fragility of feeling only after a relationship breaks.",
        "It may be only in the interval after something has ended that we can feel a little closer to the real world and to ourselves.",
        "I suddenly remembered high school at Yali. Those were days when a pure desire to express overwhelmed decline, days when deep conversations belonging to nature could appear anytime, anywhere. They were also the days when my worldview was being opened up. Maybe after growing up, more thoughts no longer need so many other eyes observing them. Maybe not. What seems foreseeable is that the days belonging to nature are gradually passing, and you and I both need to learn to embrace the bonsai."
      ],
      "date": "18 May 2026",
      "note": "vol.7 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/sazanami/01.jpg",
        "caption": "cover"
      },
      {
        "src": "assets/content/radio/sazanami/02.jpg",
        "caption": "观音·听时2"
      },
      {
        "src": "assets/content/radio/sazanami/03.jpg",
        "caption": "麓湖公园1"
      },
      {
        "src": "assets/content/radio/sazanami/04.jpg",
        "caption": "HKMOA2"
      }
    ],
    "cover": "assets/content/radio/sazanami/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20260125%20-%20Sazanami.mp3",
    "durationSeconds": 461,
    "durationLabel": "07:41",
    "sizeBytes": 7329357,
    "sizeLabel": "7.0 MB",
    "bitrateKbps": 127,
    "tags": {}
  },
  {
    "id": "tomadou",
    "volume": "vol.6",
    "category": "radio",
    "publishedAt": "2026-04-20",
    "zh": {
      "title": "20250907 - Tomadou",
      "heading": "「即兴演奏」",
      "body": [
        "港硕的第二学期好像过的比第一学期快很多，居然在这么长的时间里没有更新过一期电台而毫无知觉，总之还是在生活的夹缝里找到些空闲。其实这是一期存货，原本是去年学期初，在西贡游船活动后回来摸的，代表了当时的情绪以及语彙。其实我有非常多存货，但是自己还没有听顺耳，也就没有发的冲动，比起“有感而弹”的生产逻辑和练琴扒曲的积累本身，更慢的反而是自己听顺耳的这个过程。事实上我很久之前觉得这一期的内容其实并不怎么样，发出来夺样银笑换，但是近期拿出来重听又感觉实在是不赖，总之这的确是所有创作者都会经历的心理，总而言之趁这个念头，抓紧发了最好。（顺便预告，这样的“遗珠”还有几期）",
        "虽然东西是旧的，但还是聊点新东西吧。",
        "你广的春天实在令人苦恼，湿黏的空气让人莫名焦虑，迷惘，时间仿佛被这种粘稠的焦虑感模糊掉了，让人感觉疲惫而蹉跎。招聘压力和这勾石天气应该各打五十大板。这样以后最大最严重最恶劣的后果可能是，会导致像我这样的以散步为生的人不太情愿出门散步，存在主义的体验亦有高低之分，比起活活被闷死，我更愿意在空调房里开开gt7",
        "散步和开gt7在我看来是很类似的事情，都是我专门用来听播客的美妙时间，在其中一半的我在纽北一圈圈飞驰，感受每一个弯道，循迹路线，开油时机，救车与预判，在这个过程中，0.5s的操作决策都会有截然不同的反馈，注意力需要焊死在驾驶上；而另一半的我，能够完全沉浸在播客里，能完全跟上耳机里的一字一句，嬉笑怒骂，甚至有置身于一种低压的虚拟社交现实中的幻觉。意识体验被完全分离成两个部分，而同时在记忆里又会相互锚定，我能在某条赛道上想起来当初在这里听过哪期播客，在重听某一期时又能想起来开哪辆车破了哪个圈速。这个过程和散步或跑步带给我的体验几乎没有任何区别，甚至注意力长期高度集中，我反而会感到更多的惬意与对自我存在的确认",
        "我喜欢 甚至是沉迷这样的时间，我会希望走更远的路通勤，会希望再晚一点下车，会原谅自己在gt7里莫名出现的失误，这样就又可以重开一轮。。。因为一旦脱离这种屏蔽，就又不得继续面对潮水般回流的生活的压力，以及未来的仿佛永不可摆脱的一轮又一轮的压力，以及更可怖的在压力中持续的  迷茫与“不能逃避” 的循环。身处逆境中心的人是不会真的把逆境当作生活的幸存者偏差的，身处顺境的人同样。绝望之为虚妄，正与希望相同。我不想承认迷茫是我真实的生活，我不想在面对每次挑战，每轮压力时，我都只能对自己说“不能逃避”，于是我激烈地思考，长久地锻炼理智与世界观，竭尽全力在一轮又一轮的压力中寻找所谓理想主义的方向，同时维护真实的自我的存在。比起受社达压力浸泡，迷茫 或者说逻辑不通顺的人生更让我感到痛苦；同样正过来说，比起社达压力被缓解，明确努力在做的事情与自己想做的事情尚存在不小的重合，并能够持续的有机会触碰真实的生活 更让我感到健康。",
        "感觉一到招聘季就会发类似的牢骚，吐类似的苦水，呻类似的吟，值得高兴的是，日子并没有偏离上述这种健康水平太远，这实在值得庆贺。事实上，当救车的能力足够了，车手自然会更大胆地开油，至于新的偏差的出现，能做的其实只有等待。"
      ],
      "date": "2026.04.20",
      "note": "vol.6 / 即兴演奏"
    },
    "en": {
      "title": "20250907 - Tomadou",
      "heading": "“Improvisation”",
      "body": [
        "The second semester of my Hong Kong master’s seems to have passed much faster than the first. Somehow I went all this time without releasing a radio episode and barely noticed. At last I found a little room in the cracks of life. This one is actually from the archive: I played it near the start of the previous academic year, after returning from a boat trip in Sai Kung, and it carries the emotions and vocabulary of that time. I have a great deal sitting in the archive, but until something begins to sound right to me, I have no impulse to release it. Compared with the production logic of “feeling something and playing,” or with the accumulation of practice and transcription, the slowest process is simply learning to like the recording. For a long time I thought this episode was not very good and that publishing it would only invite ridicule. Recently I listened again and thought: no, this is actually rather nice. Every creator goes through this. Better catch the thought and release it quickly. (There are several more “lost gems” like this waiting.)",
        "The recording is old, but I can still talk about something new.",
        "Spring in Guangdong is exasperating. The wet, sticky air produces anxiety and confusion for no apparent reason. Time itself seems blurred by the viscous unease, leaving me tired and feeling that I have let it slip away. Recruitment pressure and this god-awful weather deserve equal blame. The gravest consequence is that people like me, who live by walking, become reluctant to go outside. Existential experience has its hierarchy too; rather than be suffocated alive, I would prefer to stay in an air-conditioned room and drive in GT7.",
        "Walking and playing GT7 feel very similar to me. Both are beautiful stretches reserved for podcasts. One half of me flies lap after lap around the Nürburgring Nordschleife, feeling every corner, line, throttle point, recovery, and prediction. A decision made in half a second produces a completely different response, so my attention has to be welded to the driving. The other half can disappear entirely into the podcast, following every word, every joke and outburst, almost hallucinating a low-pressure form of virtual social life. Conscious experience splits cleanly in two, while memory anchors the halves together. On a certain track I remember which podcast I once heard there; replaying an episode, I remember which car broke which lap record. The experience is almost identical to walking or running. Sustained concentration can even leave me feeling more at ease and more certain of my own existence.",
        "I like these stretches of time—perhaps I am addicted to them. I want a longer commute, want to get off one stop later, forgive an unexplained mistake in GT7 because it gives me an excuse to restart another lap. Once the shield drops, the pressures of life rush back like a tide: the apparently endless rounds waiting in the future, and, worse, the ongoing loop of confusion and “you cannot run away.” Someone at the centre of adversity cannot honestly treat adversity as survivorship bias; nor can someone in favourable circumstances. Despair is as hollow as hope. I do not want to accept confusion as my real life. I do not want “you cannot run away” to be the only thing I can tell myself whenever I face another challenge or another round of pressure. So I think fiercely, train my reason and worldview over long periods, and do everything I can to find a direction that deserves to be called idealistic while preserving the existence of a real self. More than being soaked in the pressure of social Darwinism, I suffer from a confused life whose logic does not hold. Conversely, more than the relief of that pressure, what makes me feel healthy is knowing that what I work to do still overlaps substantially with what I want to do, and that I can keep finding chances to touch real life.",
        "Recruitment season always seems to bring out this same complaining, bitterness, and groaning. Happily, life has not drifted too far below the “healthy” level described above. That is worth celebrating. Once a driver becomes good enough at saving the car, they naturally grow bolder on the throttle. As for the new deviations that follow, all one can do is wait."
      ],
      "date": "20 Apr 2026",
      "note": "vol.6 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/tomadou/01.jpg",
        "caption": "cover"
      },
      {
        "src": "assets/content/radio/tomadou/02.jpg",
        "caption": "观音·听时1"
      },
      {
        "src": "assets/content/radio/tomadou/03.jpg",
        "caption": "红磡路演"
      },
      {
        "src": "assets/content/radio/tomadou/04.jpg",
        "caption": "HKMOA1"
      }
    ],
    "cover": "assets/content/radio/tomadou/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20250907%20-%20Tomadou.mp3",
    "durationSeconds": 854,
    "durationLabel": "14:14",
    "sizeBytes": 17085565,
    "sizeLabel": "16.3 MB",
    "bitrateKbps": 160,
    "tags": {}
  },
  {
    "id": "wasure",
    "volume": "vol.5",
    "category": "radio",
    "publishedAt": "2026-01-28",
    "zh": {
      "title": "20260110 - Wasure",
      "heading": "「即兴演奏」",
      "body": [
        "假后回到香港的第一次摸琴，时长也意外的提升到了17分钟，我当然是没有实际即兴17分钟的能力的，免不了有大量的犹豫与弹劈的地方，但是如果是提前反复编排过的东西，反而更接受不了失误，听感也会显得刻意不自然。因此，只要在一大段东西里，有非常值得一听的即兴的编排设计，和色彩氛围的起伏；在一小段即兴乐句中，有一两处非常值得一听的旋律，织体，voicing排列，和声切换的听感，那么我就会认为这是种「Aha! Moment」般的体验，这是种只能被捕捉不能被制造的体验，不管是在当时弹出来的瞬间，还是在后面回听的时刻，值得让我忽略瑕疵，然后不要脸地扔到电台上。",
        "〈坪洲之歌〉 （節錄）  王兆基",
        "樹冠跌落的微笑\n讀詩如偶然的船期\n接近我的碼頭\n或者不\n\t\t——《阿修羅時間》",
        "康本二楼的cafe，窗户上经常会摘抄些东西",
        "读诗与写诗，或者说，艺术作品的欣赏与创作本身，所带来的触动并非是随时可得的，很多时候都只是偶然的交会，有时会错过，有时会抵达，但只要感知「Aha! Moment」的开关一直开着，码头就依然在那儿，你就无需对此感到焦虑",
        "但是，发船的人，确是焦虑的。最近想认真练一练，扒一扒，我目前最喜欢的坂本龙一的专辑《async》，于是也把相关的访谈也找来看了一遍，在2016年春天坂本龙一在制作这张专辑的时候，接受了日本 The Japan Times 的采访，里面提到了一句令我深深共鸣的话",
        "「我经常会萌生许多想法，但如果不去实践这些想法，它们很快就会变得愚昧陈腐」",
        "我靠太对了，一段我这样的即兴或者是正式作品的发布，实际上只有一个不长的窗口期，这个窗口期正比于作者的脸皮和作品的质量，在这期间你有最大的好奇和勇气去改进去发布，同时你也有对作品本身最同频的感知与最满意的触动；若在窗口期又正好遇到了拖延或者其他的不可抗力的因素，一旦过了这个窗口期，这个作品大概率就会自动归为所谓demo的垃圾堆里了（就像我其实在备忘录里距离上一期起码又屯了4期10分钟以上的即兴 被荒废了，还有不计其数的等待被发展成成曲的demo，还有永远也发不出的专辑。。。）我的脸皮很薄，手活也很差，对曲子的理解也很有限，所以确实需要鼓励，比如电台这种非正式的形式，比如第一期提到的清野拓巳先生，比如G团的小伙伴们，比如坂本龙一先生",
        "从更大的时间尺度上更是如此，我虽然仍然时常会听3 4 年前写的被戏称为“日本动画片”的曲子，又或者是高中19 20年刚刚接触音乐创作时拿库乐队编的连音符力度都没有调过的电子乐和编制乐的东西，理性上我知道这些都是非常宝贵的创作，但感性上我可能永远也不会把他们当作新的专辑，ep，一本正经的发布出来，而且我对他们的修改和完善的念头也在逐年减少；而我清楚记得的是，对他们的创作与制作同样是耗费了相当的时间的，甚至他们中的大部分都被我规划到某些未存在、未发行、中二的“专辑”过",
        "「事实上，你每时每刻都在改变着。好奇心、野心无时无刻都在改变；你的耳朵、你喜欢的音乐，甚至是你做的音乐也会与之改变」",
        "正是这样，甚至是人生经历不断推进的感受阈值，审美倾向，与所体验的更高量级的情绪，都会有深入挖掘的冲动，会有把过去的自己摒弃的冲动。遗忘无时无刻不在发生。遗憾无时无刻不在发生。我为现在做的氛围即兴和很多又短又怪的曲子而骄傲，但我不喜欢以前做的那些伪电子音乐，伪编制乐，伪野田洋次郎音乐；而我又清楚的知道，将来某一天，我也会讨厌我现在做的这些伪坂本龙一音乐，伪青叶市子音乐。但总之，我还是不希望任何一个时期，至少现在这个时期，的东西完全被粗暴的认为不值得被表达出来，他们的“离去”其实很重要，只是我仍然需要进化，无论是脸皮还是手活",
        "焦虑其实并没有必要，毕竟，做这些东西的目的首先是为了取悦自己，宣泄情绪，满足表达欲。在这个冷漠 充满拒绝的世界，至少在这段时间 这段人生 这段琴声之中，偶然的船期不会拒绝我，他们只是有些颠簸罢了",
        "而倘若这些颠簸的船期 于某个\n偶然的未来\n偶然的人生\n偶然地接近你的码头\n那也将是非常美妙的一件事"
      ],
      "date": "2026.01.28",
      "note": "vol.5 / 即兴演奏"
    },
    "en": {
      "title": "20260110 - Wasure",
      "heading": "“Improvisation”",
      "body": [
        "This was the first time I touched a piano after returning to Hong Kong from the holiday, and somehow the recording grew to seventeen minutes. I obviously cannot truly improvise for seventeen minutes; there are long hesitations and plenty of mistakes. Yet if I arrange something repeatedly in advance, I become even less able to tolerate errors, and the result starts to feel deliberate and unnatural. So if a long improvisation contains an arrangement worth hearing, a rise and fall of colour and atmosphere—or if a short phrase contains one or two melodies, textures, voicings, or harmonic turns worth hearing—I count that as an “Aha! Moment.” It can only be captured, never manufactured, whether in the instant it comes through my hands or later when I listen back. That is enough for me to overlook the flaws and shamelessly throw the whole thing onto the radio.",
        "From “Song of Peng Chau” (excerpt), by Wong Siu-kei:",
        "“A smile falling from the crown of a tree / Reading poetry, like an accidental sailing / Approaches my pier / Or does not.” — Asura Time",
        "The café on the second floor of Koon Pun often copies passages like this onto its windows.",
        "Reading and writing poetry—or experiencing and making art—do not offer their touch on demand. Most of the time it is only an accidental meeting. Sometimes it misses us; sometimes it arrives. As long as the switch that senses the “Aha! Moment” stays on, the pier remains there, and there is no need to be anxious about it.",
        "The person dispatching the boat, however, is anxious. Recently I wanted to practise and transcribe async, currently my favourite Ryuichi Sakamoto album, so I also went through the interviews around it. While making the record in spring 2016, Sakamoto told The Japan Times something that resonated deeply with me: “I often have many ideas, but if I don’t put them into practice, they quickly become foolish and stale.”",
        "God, yes. An improvisation like mine—or a formally finished piece—really has only a short window in which it can be released. The length of that window is proportional to the creator’s nerve and the quality of the work. During it, curiosity and courage to improve and publish are at their highest, and the creator remains most closely tuned to the piece and most capable of feeling its pull. If procrastination or some other force intervenes, once the window closes the piece will probably be sorted automatically into the rubbish heap called “demos.” I have at least four improvisations longer than ten minutes sitting in my notes since the previous episode, abandoned; countless demos waiting to become full pieces; albums that will never be released. My skin is thin, my hands are clumsy, and my understanding of music is limited, so I do need encouragement: the informality of a radio, Takumi Seino from the first episode, friends from G Group, Ryuichi Sakamoto.",
        "The same is true on a larger timescale. I still sometimes listen to the pieces I wrote three or four years ago that friends jokingly called “Japanese animation music,” or the electronic and ensemble tracks I arranged in GarageBand in high school, in 2019 and 2020, before I even adjusted the velocity of linked notes. Rationally, I know these creations are precious. Emotionally, I may never treat them as a new album or EP and release them with a straight face. My desire to revise and complete them diminishes each year. Yet I remember clearly that they also took a great deal of time to write and produce, and that most of them once belonged to plans for some nonexistent, unreleased, embarrassingly dramatic “album.”",
        "“In fact, you are changing at every moment. Your curiosity and ambition are always changing; your ears, the music you like, and even the music you make will change with them.”",
        "Exactly. As life advances, the threshold of feeling changes, taste changes, and stronger emotions arrive. Each creates the urge to dig deeper and to discard the person one used to be. Forgetting happens constantly. Regret happens constantly. I am proud of the atmospheric improvisations and the many short, strange pieces I make now, but I dislike the pseudo-electronic music, pseudo-ensemble music, and pseudo-Yojiro Noda music I made before. And I know that one day I will also dislike the pseudo-Ryuichi Sakamoto and pseudo-Ichiko Aoba music I make now. Still, I do not want the work from any period—at least this period—to be dismissed wholesale as unworthy of expression. Its departure matters. I simply still need to evolve, in nerve as much as in technique.",
        "The anxiety is unnecessary, really. The first purpose of making these things is to please myself, discharge emotion, and satisfy the need to express. In this cold world, full of rejection, at least within this stretch of time, this life, and this piano sound, the accidental sailings will not reject me. They are only a little rough.",
        "And if these rough sailings, in some accidental future, some accidental life, happen to approach your pier, that too would be a wonderful thing."
      ],
      "date": "28 Jan 2026",
      "note": "vol.5 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/wasure/01.jpg",
        "caption": "cover"
      },
      {
        "src": "assets/content/radio/wasure/02.jpg",
        "caption": "康本1"
      },
      {
        "src": "assets/content/radio/wasure/03.jpg",
        "caption": "太平山1"
      },
      {
        "src": "assets/content/radio/wasure/04.jpg",
        "caption": "沅江1"
      }
    ],
    "cover": "assets/content/radio/wasure/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20260110%20-%20Wasure.mp3",
    "durationSeconds": 1027,
    "durationLabel": "17:07",
    "sizeBytes": 20545222,
    "sizeLabel": "19.6 MB",
    "bitrateKbps": 160,
    "tags": {}
  },
  {
    "id": "saudade",
    "volume": "vol.4",
    "category": "radio",
    "publishedAt": "2025-11-04",
    "zh": {
      "title": "20251023 - Saudade",
      "heading": "「即兴演奏」，后面一小段theme源自《BB》坂本龙一",
      "body": [
        "依旧瞎弹，但是本次更新大幅下调了瞎变调的比例，也是用上了新手机语音备忘录的录音室功能，听感应该要好上不少，可喜可贺",
        "源头在于，eva新剧场版 终，要引进，最后忍住了没有提前重温，但是仍然记得上次看，最打动我的始终是这两个画面：",
        "一个是",
        "我想去收麦子\n想去再多抱抱燕\n想和喜欢的人永远在一起\n再见了",
        "一个是",
        "啊 讨厌 别拍摄啊\n抱歉 只是想给今天留个记录下来\n是吗 那就随你便了",
        "（新剧场版真的还是有他的魅力的",
        "eva的世界是一个充满痛苦的世界，而一段痛苦中最宝贵的东西自然是其中的美好。我个人非常喜欢破和终，是因为这两部有全系列不多的有活人味的部分的存在，让真嗣后面的决定变得合理，也让处在真实的生活中的我们重新意识到，日常的点滴的珍贵，真实的生活，真实的情感的珍贵",
        "但很少有人能意识到的是 这件事反过来的版本同样成立，那就是",
        "一段美好中最宝贵的东西就是其破碎时的痛苦与心碎",
        "无论是自我觉醒后死去的白丽，还是融入大家后死去的黑丽（不想提eva了 不是拉踩香香的意思）；砍下艾伦头颅的三笠；在辛美尔葬礼上痛哭的芙莉莲；或者是深深无奈而又深深思念着什么的 自我和解而又反复梦到着什么的 迷茫畏惧而又无比渴望着什么的 深陷这种 真实的生活 真实的情感 中的你我",
        "只有与生活主旋律相反的东西才更容易被我们记住，这是基本的幸存者偏差。只有经历了最青涩最美好的青春的人，才会对错过的人和事有最难以忘却的记忆与伤感。而这种偏差 本身也是美好的 因为他们最能体现你真实的生活 真实的情感。而可惜的是 无论是青春本身的美好，还是点缀其上的痛苦与心碎 身在青春中的人往往无法意识到其珍贵性，通常也无法意识到这些东西发生次数的有限性。而又可以预见的是，这些感知能力本身，随时间流逝，是会突然消失的，恰如死亡一样。因此他们的出现，种种遗憾 种种思念 种种痛苦，也都无比珍贵，恰如生命一样。明白这些我才能说出真嗣那句话：“我没事，我想我可以承受 痛苦和心碎。”",
        "当所有感知类似美好与痛苦的能力都随年纪消逝了 我还能确认自身一切的真实性吗\n拍脑袋想想的确可怕 也许那时候的人有自己的办法",
        "回想22年的时光，的确错过了不少次重要的时刻，但好在，也抓住了一些。我早已不再追责 一切的发生与我的努力 有没有相关性，不管是美好还是痛苦，我只知道 剩下的工作就是去感受它 然后写点文字 编点曲子 弹点琴",
        "今天是生日，也是本轮盈凸月的最后一天，明天就将是满月升起\n我还能多少次看到满月升起",
        "「How many more times will you watch the full moon rise?\nPerhaps twenty.\nAnd yet it all seems limitless.」",
        "后记：「Saudade」 其实是之前刷xhs刷到的“主理人”装逼词汇，是葡萄牙语，以难以翻译闻名，大致意为一种释怀而又思念的感觉，是一种“健康的”思念。我认为它完美统一上面两个版本的珍贵。不对不对 对吗 哦对的对的对的",
        "后记2:《NEWTYPE》5月刊里有新剧场版《终》的专访，里面副导演谷田部提到：\n“健介把摄像机转向明日香的那场戏，有指示说——这里是‘像爱情场景一样的东西’。”\nケンスケがアスカにビデオカメラを向けるシーンは「ここはラブシーンのようなものなんだよ」と指示がありました。",
        "后记3:最后的一段话来自 坂本龙一 的自传 《我还能看到多少次满月升起》中对电影《遮蔽的天空》中台词的引用，也是《fullmoon》中的念白。（同时也是未来某期电台的预告x"
      ],
      "date": "2025.11.04",
      "note": "vol.4 / 即兴演奏"
    },
    "en": {
      "title": "20251023 - Saudade",
      "heading": "“Improvisation” — a short theme near the end comes from Ryuichi Sakamoto’s “BB.”",
      "body": [
        "Still playing blindly, though this update dramatically reduces the amount of blind key-changing. I also used the studio mode in Voice Memos on my new phone, so it should sound noticeably better. Cause for celebration.",
        "This began with the news that Evangelion: 3.0+1.0 was coming to cinemas here. I managed not to rewatch it in advance, but I still remembered the two moments that moved me most the last time.",
        "One was: “I want to harvest the wheat. I want to hold Tsubame a little more. I want to stay with the person I love forever. Goodbye.”",
        "The other was: “Oh, come on. Don’t film me.” “Sorry. I only wanted to leave a record of today.” “Is that so? Then do whatever you want.”",
        "(The Rebuild films really do have their own charm.)",
        "Evangelion’s world is full of pain, and the most precious thing inside a painful stretch is naturally whatever beauty it contains. I especially like 2.0 and 3.0+1.0 because they contain some of the few moments in the series that feel inhabited by living people. They make Shinji’s later decision believable and remind those of us in real life how precious ordinary moments, real life, and real feelings are.",
        "What few people notice is that the reverse is equally true: the most precious thing inside a beautiful stretch may be the pain and heartbreak of its breaking.",
        "Rei II dying after awakening to herself; Rei Q dying after becoming part of the village; Mikasa cutting off Eren’s head; Frieren sobbing at Himmel’s funeral—or you and me, helplessly missing something, making peace with ourselves yet dreaming it again and again, lost and afraid yet longing beyond measure, sunk deep in this real life and these real feelings.",
        "What runs against the main melody of life is often what we remember most clearly. It is a basic kind of survivorship bias. Only someone who has lived through the greenest and most beautiful youth can carry such unforgettable sadness for the people and moments they missed. That bias is beautiful in itself, because it reveals real life and real feeling most clearly. The pity is that, whether it is youth’s beauty or the pain and heartbreak scattered across it, those living inside youth rarely recognise its value—or how few times such things will happen. We can also foresee that the ability to feel them may suddenly disappear with time, much like death itself. So their appearance—all that regret, longing, and pain—is as precious as life. Only after understanding this can I repeat Shinji’s words: “I’m all right. I think I can bear pain and heartbreak.”",
        "When age has worn away every ability to feel beauty and pain, will I still be able to confirm the reality of anything in me? It is frightening to imagine. Perhaps people at that age have their own methods.",
        "Looking back at 2022, I did miss several important moments. Fortunately, I caught some too. I no longer prosecute the question of whether anything that happened was connected to my own effort. Beautiful or painful, I only know what remains to be done: feel it, write something, compose something, play the piano.",
        "Today is my birthday, and the last day of this waxing gibbous moon. Tomorrow the full moon will rise. How many more times will I watch it rise?",
        "“How many more times will you watch the full moon rise? Perhaps twenty. And yet it all seems limitless.”",
        "Postscript: “Saudade” was originally one of those affected words I saw people using on Xiaohongshu. It is Portuguese and famously hard to translate: roughly, a longing that contains acceptance—a “healthy” kind of missing. To me it holds the preciousness of both versions above in a single word. No, wait. Does it? Yes. Yes, yes, yes.",
        "Postscript 2: In the May issue of NEWTYPE, assistant director Katsuichi Yatabe discussed the scene in 3.0+1.0 where Kensuke points the video camera at Asuka: “For the scene where Kensuke turns the camera toward Asuka, the direction was: ‘This is something like a love scene.’”",
        "Postscript 3: The final quotation comes from Ryuichi Sakamoto’s memoir How Many Full Moons Will I See?, where he cites a line from the film The Sheltering Sky. It is also spoken in “fullmoon.” (And it previews a future radio episode.)"
      ],
      "date": "4 Nov 2025",
      "note": "vol.4 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/saudade/01.jpg",
        "caption": "cover"
      },
      {
        "src": "assets/content/radio/saudade/02.jpg",
        "caption": "大埔幸汇"
      },
      {
        "src": "assets/content/radio/saudade/03.jpg",
        "caption": "麓湖公园1"
      },
      {
        "src": "assets/content/radio/saudade/04.jpg",
        "caption": "birds"
      }
    ],
    "cover": "assets/content/radio/saudade/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20251023%20-%20Saudade.mp3",
    "durationSeconds": 636,
    "durationLabel": "10:36",
    "sizeBytes": 12715280,
    "sizeLabel": "12.1 MB",
    "bitrateKbps": 160,
    "tags": {}
  },
  {
    "id": "kazeato",
    "volume": "vol.3",
    "category": "radio",
    "publishedAt": "2025-10-20",
    "zh": {
      "title": "20250921 - Kazeato",
      "heading": "「即兴演奏」，后面theme源自《Amore》坂本龙一",
      "body": [
        "依旧瞎弹，很多完全掉拍的地方，有些地方的思考时间也过长了。但总的来说，这次的曲子我稍微满意了一点，所以后期加入了一些氛围的音源，捡起了久违的制作的感觉。这是第一首在香港房东家钢琴弹的，并且打算发出来的东西，有趣的是，房东的钢琴极其走音，为了和音源能合起来，logic上往回拉了整整40个音分。至于调琴一事——有闲钱再议。",
        "「kazeato」意味“風跡”——风的痕迹。这是台风那一天弹的。我对桦加沙的第一印象是昏黄，半夜被吵醒，雨成了风的向量场，瞬间演化为混沌的形态。昏黄的路灯照着那胶体般的空气，我看见风的痕迹——光在涨落。外面比平时更亮，亮得诡异，像世界在崩塌前最后一次发光。",
        "人们的生活是需要这种“末日感”的。我们往往会对台风怀有某种期待，这种期待来源于世界巨大的真实对个人生活的真实的碾压与冲刷。台风很像一种“巨大沉默之物（BDO）”，它将那种对个体压倒性的真实具象化，也在社会层面上，构成了一种瞬间的公平。在这之后，BDO强迫所有人面对真实的生活，面对真实的世界，面对真实的自己。在现代社会，只有通过这样，很多人才能够意识到自己的存在。  存在主义是我最近不断回到的主题。最近度过了在我人生的所有阶段里可以说是最不“健康”的一段人生了，增长的焦虑和降低的自信中间本还隔着一层厚厚的理智，现在这层理智仿佛变薄了相当多。我经常会在连续5个小时浸泡在焦虑与恐惧中，直到突然意识到自己什么都不会后，离开座位，双腿发软。这段日子像是无绳攀岩，机会如峭壁上的手点，繁星般密布在我周围，当我奋力伸手去够时却发现，无数的机会只是幻象。当然，仍然不能逃避。我从未如此需要一个正面的结果，来打断这循环。前几天，终于有了一点松动，生活短暂地回到了“健康”的节奏，我才有力气发布新一期电台。",
        "说到底，我需要一场“台风”。\n我需要某种巨大的、不可逃避的、真实的东西，在伪善的机遇与自我欺骗之间，撕开一条缝，让那些“显而易见”的真相重新显现。",
        "「人生最大的谎言就是\n\t——不活在此时此刻」",
        "无论过去多少遗憾，无论未来光明与否，时间的流逝永不会停止，人生网格的吸附亦不能逃避\n因此，专注体验当下是很有必要的，弹琴是很有必要的，散步是很有必要的，感受风的吹拂是很有必要的，看到月亮是很有必要的。。。当个事办。"
      ],
      "date": "2025.10.20",
      "note": "vol.3 / 即兴演奏"
    },
    "en": {
      "title": "20250921 - Kazeato",
      "heading": "“Improvisation” — the later theme comes from Ryuichi Sakamoto’s “Amore.”",
      "body": [
        "Still playing blindly. There are many places where I lose the beat completely, and some pauses where I think for far too long. Overall, though, I was a little happier with this one, so I added some atmospheric sounds afterwards and rediscovered the long-lost feeling of producing. This was the first piece I played on my Hong Kong landlord’s piano and intended to release. Amusingly, the piano was wildly out of tune; to make it sit with the other sounds, I had to pull everything in Logic down by a full forty cents. As for tuning the piano—we’ll discuss that when I have spare money.",
        "“Kazeato” means “the trace of wind.” I played it on the day of the typhoon. My first impression of Ragasa was a sickly yellow light. The noise woke me in the middle of the night; rain became a vector field for the wind and instantly evolved into chaos. Yellow street lamps lit the colloidal air, and I could see the wind’s traces—the light itself fluctuating. Outside was brighter than usual, uncannily bright, as if the world were giving off one final glow before collapsing.",
        "People need this sense of apocalypse in their lives. We often hold a strange anticipation for typhoons. It comes from the enormous reality of the world crushing and washing over the smaller reality of an individual life. A typhoon resembles a “Big Dumb Object”: it makes that overwhelming reality tangible and, on a social level, creates an instant of equality. It forces everyone to face real life, the real world, and their real selves. In modern society, many people seem able to notice their own existence only through something like this.",
        "Existentialism is a theme I have kept returning to lately. I have just lived through what may be the least “healthy” stretch of my life so far. There used to be a thick layer of reason between rising anxiety and falling confidence; now it feels considerably thinner. I can spend five hours submerged in fear and anxiety, until I suddenly realise I know how to do nothing, leave my chair, and find my legs weak beneath me. These days feel like free solo climbing. Opportunities surround me like handholds scattered across a cliff, but when I strain to reach them, countless holds turn out to be illusions. Still, there is no escaping. I have never needed a positive result so badly—something to break the loop. A few days ago, things finally loosened a little. Life briefly returned to a “healthy” rhythm, and I found the strength to publish another episode.",
        "In the end, I need a typhoon. I need something immense, unavoidable, and real to tear open a gap between hypocritical opportunity and self-deception, so that the “obvious” truths can become visible again.",
        "“The greatest lie in life is this: not living here and now.”",
        "However many regrets lie behind us, however bright or dim the future may be, time never stops, and there is no escaping the grid snapping our lives into place. So it is necessary to attend to the present. Playing the piano is necessary. Walking is necessary. Feeling the wind is necessary. Seeing the moon is necessary. Treat it as something that needs doing."
      ],
      "date": "20 Oct 2025",
      "note": "vol.3 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/kazeato/01.jpg",
        "caption": "cover"
      },
      {
        "src": "assets/content/radio/kazeato/02.jpg",
        "caption": "大埔桥洞"
      },
      {
        "src": "assets/content/radio/kazeato/03.jpg",
        "caption": "大埔通道"
      },
      {
        "src": "assets/content/radio/kazeato/04.jpg",
        "caption": "Adlermeme"
      }
    ],
    "cover": "assets/content/radio/kazeato/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20250921%20-%20Kazeato.mp3",
    "durationSeconds": 716,
    "durationLabel": "11:56",
    "sizeBytes": 14325467,
    "sizeLabel": "13.7 MB",
    "bitrateKbps": 160,
    "tags": {}
  },
  {
    "id": "itone",
    "volume": "vol.2",
    "category": "radio",
    "publishedAt": "2025-08-16",
    "zh": {
      "title": "20250806 - Itone",
      "heading": "「即兴演奏」，部分chord 源自《iam POD (0%)》青叶市子",
      "body": [
        "依旧瞎弹，用了类似吉他的拨弦类音色。去年开始很喜欢用吉他音源来当键盘音色写东西，即便是在键盘上弹，吉他音色优秀的动态仍然令人着迷（虽然录出来依托",
        "「Itone」 意味“糸音”——丝的声音，串联过往的思绪。随手摸出两小节听得过去的东西，于是点开录音，记录下乐句发展的过程。所谓发展，其实就是不断预判的过程，预判这样的音的组合能否带来好的听感。而这种预判，往往建立在一些积累之上：曾经自己写过的片段，或者扒过、练过的别人的曲子。所以这个过程本质上就是一个gpt（对的，对吗？",
        "于是，思绪在弹奏中时常会“误入”一段自己曾经的作品，或某个扒过的旋律。这是种美妙的体验，那一刻我会想起，写下或练习这段的时候，那时的我在哪里、在做什么、又在想些什么，会想起那晚散步，月光冷静而原样地存在，我想不会有比这更加真实存在的东西了",
        "烈日之下的校园，大雨砸向溪村，微风混合落叶剥离了我生活的真实，还给我真实的生活；炎热混合沉默剥离了我情感的真实，还给我真实的情感。回过神，谱架上还有半瓶没喝完的养乐多",
        "靠近下一小节时，会突然忘了——“咦，这里怎么弹来着？”——于是先胡乱应付一下，哦哦想起来了。然后“嗯，好听，我是天才”"
      ],
      "date": "2025.08.16",
      "note": "vol.2 / 即兴演奏"
    },
    "en": {
      "title": "20250806 - Itone",
      "heading": "“Improvisation” — some of the chords come from Ichiko Aoba’s “iam POD (0%).”",
      "body": [
        "Still playing blindly, this time with a plucked, guitar-like sound. Since last year I’ve grown fond of writing on keys with guitar patches. Even when played from a keyboard, the dynamics of a good guitar sound remain fascinating—though the recording quality here is held together by hope.",
        "“Itone” means “the sound of thread”: a sound that strings together thoughts from the past. I happened upon two bars that sounded all right, opened the recorder, and kept the process of the phrase developing. “Development” here is really an endless sequence of predictions: will this combination of notes feel good? Those predictions rest on things accumulated over time—fragments I once wrote, or other people’s pieces I transcribed and practised. So the process is basically a GPT. Yes. Right?",
        "While playing, my thoughts often wander by accident into something I once wrote, or a melody I once transcribed. It is a wonderful feeling. In that moment I remember where I was when I wrote or practised it, what I was doing, and what was on my mind. I remember a walk that night, the moonlight existing calmly and unchanged. I cannot imagine anything more real than that.",
        "A campus under a brutal sun; rain hammering Xicun; a breeze mixed with fallen leaves stripped the reality from my life and returned real life to me. Heat mixed with silence stripped the reality from my feelings and returned real feeling to me. Then I came back to myself and noticed half a bottle of Yakult still sitting on the music stand.",
        "As the next bar approaches, I suddenly forget—“Wait, how did this part go?”—so I bluff my way through it for a moment. Oh, right, now I remember. Then: “Mm. Sounds good. I’m a genius.”"
      ],
      "date": "16 Aug 2025",
      "note": "vol.2 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/itone/01.jpg",
        "caption": "cover"
      }
    ],
    "cover": "assets/content/radio/itone/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20250806%20-%20Itone.mp3",
    "durationSeconds": 431,
    "durationLabel": "07:11",
    "sizeBytes": 8625549,
    "sizeLabel": "8.2 MB",
    "bitrateKbps": 160,
    "tags": {}
  },
  {
    "id": "oboro",
    "volume": "vol.1",
    "category": "radio",
    "publishedAt": "2025-08-11",
    "zh": {
      "title": "20250731 - Oboro",
      "heading": "「即兴演奏」，theme chord 源自《Sadness II》坂本龙一",
      "body": [
        "哥们的fp30x铺架不稳，有塑料材质的高频异响，被上面的iphone的语音备忘录全收到了（到香港了研究下录音系统（汗",
        "依旧瞎弹，但是第一次发出来，这样的即兴于我而言，是消化和弦的过程，也是清空情绪的过程，中间会有很多弹劈和掉拍的地方，手活有限",
        "看了林师的视频，他的老师清野拓巳Takumi seino先生曾说「作为吉他手，写作这些曲子是他的一种生活方式，如果恰巧能碰到有人喜欢听，那也是非常美妙的一件事」",
        "受到seino先生的鼓舞，之后会尝试把语音备忘录和电脑里能听的玩意，包括一些半成品demo，长即兴，丢些到电台上去"
      ],
      "date": "2025.08.11",
      "note": "vol.1 / 即兴演奏"
    },
    "en": {
      "title": "20250731 - Oboro",
      "heading": "“Improvisation” — the theme chords come from Ryuichi Sakamoto’s “Sadness II.”",
      "body": [
        "My FP-30X was sitting on an unstable stand, so the iPhone Voice Memos recording picked up every high-pitched plastic rattle. I’ll look into a proper recording setup once I get to Hong Kong. (sweats)",
        "Still just playing whatever came to mind, except this was the first time I decided to put one of these recordings out. Improvisation is how I digest chords and clear out emotion. There are plenty of wrong notes and moments where I lose the beat; my hands can only do so much.",
        "I watched one of Lin’s videos, where his teacher, Takumi Seino, said that writing these pieces was a way of life for him as a guitarist, and that if someone happened to enjoy listening, that would be a wonderful thing.",
        "Encouraged by Seino, I’m going to start throwing the listenable things from Voice Memos and my computer onto the radio: unfinished demos, long improvisations, and whatever else survives."
      ],
      "date": "11 Aug 2025",
      "note": "vol.1 / improvisation"
    },
    "photos": [
      {
        "src": "assets/content/radio/oboro/01.jpg",
        "caption": "cover"
      },
      {
        "src": "assets/content/radio/oboro/02.jpg",
        "caption": "网易云播客"
      }
    ],
    "cover": "assets/content/radio/oboro/01.jpg",
    "audio": "https://audio.aimaradio.com/radio/20250731%20-%20Oboro.mp3",
    "durationSeconds": 556,
    "durationLabel": "09:16",
    "sizeBytes": 11125467,
    "sizeLabel": "10.6 MB",
    "bitrateKbps": 160,
    "tags": {}
  }
];
const demos = [
  {
    "id": "dormiveglia",
    "title": "Dormiveglia",
    "category": "demo",
    "publishedAt": "2026-06-11",
    "versions": [
      {
        "name": "Dormiveglia",
        "filename": "Dormiveglia.mp3",
        "modifiedAt": "2025-11-28",
        "audio": "https://audio.aimaradio.com/demo/Dormiveglia.mp3",
        "durationSeconds": 72,
        "durationLabel": "01:12",
        "sizeBytes": 1445533,
        "sizeLabel": "1.4 MB",
        "bitrateKbps": 160,
        "tags": {}
      },
      {
        "name": "Dormiveglia_pt2",
        "filename": "Dormiveglia_pt2.mp3",
        "modifiedAt": "2026-06-11",
        "audio": "https://audio.aimaradio.com/demo/Dormiveglia_pt2.mp3",
        "durationSeconds": 171,
        "durationLabel": "02:51",
        "sizeBytes": 3425614,
        "sizeLabel": "3.3 MB",
        "bitrateKbps": 160,
        "tags": {}
      }
    ],
    "durationLabel": "02:51"
  },
  {
    "id": "zure",
    "title": "ZURE",
    "category": "demo",
    "publishedAt": "2026-01-20",
    "versions": [
      {
        "name": "ZURE",
        "filename": "ZURE.mp3",
        "modifiedAt": "2026-01-20",
        "audio": "https://audio.aimaradio.com/demo/ZURE.mp3",
        "durationSeconds": 69,
        "durationLabel": "01:09",
        "sizeBytes": 1385451,
        "sizeLabel": "1.3 MB",
        "bitrateKbps": 160,
        "tags": {}
      }
    ],
    "durationLabel": "01:09"
  },
  {
    "id": "augustus",
    "title": "Augustus",
    "category": "demo",
    "publishedAt": "2025-11-18",
    "versions": [
      {
        "name": "Augustus",
        "filename": "Augustus.mp3",
        "modifiedAt": "2025-11-18",
        "audio": "https://audio.aimaradio.com/demo/Augustus.mp3",
        "durationSeconds": 50,
        "durationLabel": "00:50",
        "sizeBytes": 1005631,
        "sizeLabel": "1.0 MB",
        "bitrateKbps": 161,
        "tags": {}
      }
    ],
    "durationLabel": "00:50"
  },
  {
    "id": "3068-307e-3068-3099-3046",
    "title": "とまどう",
    "category": "demo",
    "publishedAt": "2025-07-23",
    "versions": [
      {
        "name": "とまどう_v2",
        "filename": "とまどう_v2.mp3",
        "modifiedAt": "2025-05-13",
        "audio": "https://audio.aimaradio.com/demo/%E3%81%A8%E3%81%BE%E3%81%A8%E3%82%99%E3%81%86_v2.mp3",
        "durationSeconds": 90,
        "durationLabel": "01:30",
        "sizeBytes": 1805500,
        "sizeLabel": "1.7 MB",
        "bitrateKbps": 160,
        "tags": {}
      },
      {
        "name": "とまどう_pt2",
        "filename": "とまどう_pt2.mp3",
        "modifiedAt": "2025-07-23",
        "audio": "https://audio.aimaradio.com/demo/%E3%81%A8%E3%81%BE%E3%81%A8%E3%82%99%E3%81%86_pt2.mp3",
        "durationSeconds": 65,
        "durationLabel": "01:05",
        "sizeBytes": 1296635,
        "sizeLabel": "1.2 MB",
        "bitrateKbps": 161,
        "tags": {}
      }
    ],
    "durationLabel": "01:05"
  },
  {
    "id": "96e8-306e-9752-7a7a",
    "title": "雨の青空",
    "category": "demo",
    "publishedAt": "2025-06-16",
    "versions": [
      {
        "name": "雨の青空_pt1",
        "filename": "雨の青空_pt1.mp3",
        "modifiedAt": "2024-08-26",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9D%92%E7%A9%BA_pt1.mp3",
        "durationSeconds": 79,
        "durationLabel": "01:19",
        "sizeBytes": 3156554,
        "sizeLabel": "3.0 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "雨の青空_pt2",
        "filename": "雨の青空_pt2.mp3",
        "modifiedAt": "2024-09-04",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9D%92%E7%A9%BA_pt2.mp3",
        "durationSeconds": 152,
        "durationLabel": "02:32",
        "sizeBytes": 6081223,
        "sizeLabel": "5.8 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "雨の青空_pt3",
        "filename": "雨の青空_pt3.mp3",
        "modifiedAt": "2025-06-16",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9D%92%E7%A9%BA_pt3.mp3",
        "durationSeconds": 257,
        "durationLabel": "04:17",
        "sizeBytes": 5152308,
        "sizeLabel": "4.9 MB",
        "bitrateKbps": 160,
        "tags": {}
      }
    ],
    "durationLabel": "04:17"
  },
  {
    "id": "96e8-306e-96c5-793c",
    "title": "雨の雅礼",
    "category": "demo",
    "publishedAt": "2025-05-19",
    "versions": [
      {
        "name": "雨の雅礼_pt1",
        "filename": "雨の雅礼_pt1.mp3",
        "modifiedAt": "2023-02-28",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9B%85%E7%A4%BC_pt1.mp3",
        "durationSeconds": 120,
        "durationLabel": "02:00",
        "sizeBytes": 4806447,
        "sizeLabel": "4.6 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "雨の雅礼_pt2",
        "filename": "雨の雅礼_pt2.mp3",
        "modifiedAt": "2023-07-16",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9B%85%E7%A4%BC_pt2.mp3",
        "durationSeconds": 240,
        "durationLabel": "04:00",
        "sizeBytes": 9606709,
        "sizeLabel": "9.2 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "雨の雅礼_pt3",
        "filename": "雨の雅礼_pt3.mp3",
        "modifiedAt": "2023-08-28",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9B%85%E7%A4%BC_pt3.mp3",
        "durationSeconds": 264,
        "durationLabel": "04:24",
        "sizeBytes": 10566970,
        "sizeLabel": "10.1 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "雨の雅礼_pt4_Tide_bonus",
        "filename": "雨の雅礼_pt4_Tide_bonus.mp3",
        "modifiedAt": "2024-01-26",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9B%85%E7%A4%BC_pt4_Tide_bonus.mp3",
        "durationSeconds": 60,
        "durationLabel": "01:00",
        "sizeBytes": 2406317,
        "sizeLabel": "2.3 MB",
        "bitrateKbps": 321,
        "tags": {}
      },
      {
        "name": "雨の雅礼_pt4",
        "filename": "雨の雅礼_pt4.mp3",
        "modifiedAt": "2024-03-21",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9B%85%E7%A4%BC_pt4.mp3",
        "durationSeconds": 468,
        "durationLabel": "07:48",
        "sizeBytes": 18726578,
        "sizeLabel": "17.9 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "雨の雅礼_pt5",
        "filename": "雨の雅礼_pt5.mp3",
        "modifiedAt": "2025-05-19",
        "audio": "https://audio.aimaradio.com/demo/%E9%9B%A8%E3%81%AE%E9%9B%85%E7%A4%BC_pt5.mp3",
        "durationSeconds": 123,
        "durationLabel": "02:03",
        "sizeBytes": 2465353,
        "sizeLabel": "2.4 MB",
        "bitrateKbps": 160,
        "tags": {}
      }
    ],
    "durationLabel": "02:03"
  },
  {
    "id": "icity",
    "title": "icity",
    "category": "demo",
    "publishedAt": "2025-04-22",
    "versions": [
      {
        "name": "icity",
        "filename": "icity.mp3",
        "modifiedAt": "2025-04-22",
        "audio": "https://audio.aimaradio.com/demo/icity.mp3",
        "durationSeconds": 146,
        "durationLabel": "02:26",
        "sizeBytes": 5862839,
        "sizeLabel": "5.6 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "02:26"
  },
  {
    "id": "mis",
    "title": "mis",
    "category": "demo",
    "publishedAt": "2025-03-17",
    "versions": [
      {
        "name": "mis",
        "filename": "mis.mp3",
        "modifiedAt": "2025-01-01",
        "audio": "https://audio.aimaradio.com/demo/mis.mp3",
        "durationSeconds": 109,
        "durationLabel": "01:49",
        "sizeBytes": 4363411,
        "sizeLabel": "4.2 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "mis_pt2",
        "filename": "mis_pt2.mp3",
        "modifiedAt": "2025-03-02",
        "audio": "https://audio.aimaradio.com/demo/mis_pt2.mp3",
        "durationSeconds": 72,
        "durationLabel": "01:12",
        "sizeBytes": 2886970,
        "sizeLabel": "2.8 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "mis_pt3_v2",
        "filename": "mis_pt3_v2.mp3",
        "modifiedAt": "2025-03-17",
        "audio": "https://audio.aimaradio.com/demo/mis_pt3_v2.mp3",
        "durationSeconds": 264,
        "durationLabel": "04:24",
        "sizeBytes": 10545027,
        "sizeLabel": "10.1 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "04:24"
  },
  {
    "id": "6728-6f0f-308c-65e5",
    "title": "木漏れ日",
    "category": "demo",
    "publishedAt": "2024-12-04",
    "versions": [
      {
        "name": "木漏れ日",
        "filename": "木漏れ日.mp3",
        "modifiedAt": "2024-07-03",
        "audio": "https://audio.aimaradio.com/demo/%E6%9C%A8%E6%BC%8F%E3%82%8C%E6%97%A5.mp3",
        "durationSeconds": 85,
        "durationLabel": "01:25",
        "sizeBytes": 3419868,
        "sizeLabel": "3.3 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "木漏れ日_pt2",
        "filename": "木漏れ日_pt2.mp3",
        "modifiedAt": "2024-12-04",
        "audio": "https://audio.aimaradio.com/demo/%E6%9C%A8%E6%BC%8F%E3%82%8C%E6%97%A5_pt2.mp3",
        "durationSeconds": 161,
        "durationLabel": "02:41",
        "sizeBytes": 6433353,
        "sizeLabel": "6.1 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "02:41"
  },
  {
    "id": "602a-7378",
    "title": "怪獸",
    "category": "demo",
    "publishedAt": "2024-11-24",
    "versions": [
      {
        "name": "怪獸",
        "filename": "怪獸.mp3",
        "modifiedAt": "2024-11-24",
        "audio": "https://audio.aimaradio.com/demo/%E6%80%AA%E7%8D%B8.mp3",
        "durationSeconds": 38,
        "durationLabel": "00:38",
        "sizeBytes": 1542186,
        "sizeLabel": "1.5 MB",
        "bitrateKbps": 321,
        "tags": {}
      }
    ],
    "durationLabel": "00:38"
  },
  {
    "id": "6df1-96e8",
    "title": "深雨",
    "category": "demo",
    "publishedAt": "2024-11-05",
    "versions": [
      {
        "name": "深雨_pt1",
        "filename": "深雨_pt1.mp3",
        "modifiedAt": "2024-11-05",
        "audio": "https://audio.aimaradio.com/demo/%E6%B7%B1%E9%9B%A8_pt1.mp3",
        "durationSeconds": 63,
        "durationLabel": "01:03",
        "sizeBytes": 2532749,
        "sizeLabel": "2.4 MB",
        "bitrateKbps": 321,
        "tags": {}
      },
      {
        "name": "深雨_pt2",
        "filename": "深雨_pt2.mp3",
        "modifiedAt": "2024-11-05",
        "audio": "https://audio.aimaradio.com/demo/%E6%B7%B1%E9%9B%A8_pt2.mp3",
        "durationSeconds": 82,
        "durationLabel": "01:22",
        "sizeBytes": 3291345,
        "sizeLabel": "3.1 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "01:22"
  },
  {
    "id": "6e80-6708",
    "title": "満月",
    "category": "demo",
    "publishedAt": "2024-10-22",
    "versions": [
      {
        "name": "満月",
        "filename": "満月.mp3",
        "modifiedAt": "2024-10-20",
        "audio": "https://audio.aimaradio.com/demo/%E6%BA%80%E6%9C%88.mp3",
        "durationSeconds": 32,
        "durationLabel": "00:32",
        "sizeBytes": 1286186,
        "sizeLabel": "1.2 MB",
        "bitrateKbps": 321,
        "tags": {}
      },
      {
        "name": "満月_pt2",
        "filename": "満月_pt2.mp3",
        "modifiedAt": "2024-10-22",
        "audio": "https://audio.aimaradio.com/demo/%E6%BA%80%E6%9C%88_pt2.mp3",
        "durationSeconds": 104,
        "durationLabel": "01:44",
        "sizeBytes": 4166970,
        "sizeLabel": "4.0 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "01:44"
  },
  {
    "id": "3044-3061-3053-3099-306e-304a-3068",
    "title": "いちごのおと",
    "category": "demo",
    "publishedAt": "2024-08-23",
    "versions": [
      {
        "name": "いちごのおと_pt1_res",
        "filename": "いちごのおと_pt1_res.mp3",
        "modifiedAt": "2024-08-21",
        "audio": "https://audio.aimaradio.com/demo/%E3%81%84%E3%81%A1%E3%81%93%E3%82%99%E3%81%AE%E3%81%8A%E3%81%A8_pt1_res.mp3",
        "durationSeconds": 56,
        "durationLabel": "00:56",
        "sizeBytes": 2246447,
        "sizeLabel": "2.1 MB",
        "bitrateKbps": 321,
        "tags": {}
      },
      {
        "name": "いちごのおと_pt2",
        "filename": "いちごのおと_pt2.mp3",
        "modifiedAt": "2024-08-23",
        "audio": "https://audio.aimaradio.com/demo/%E3%81%84%E3%81%A1%E3%81%93%E3%82%99%E3%81%AE%E3%81%8A%E3%81%A8_pt2.mp3",
        "durationSeconds": 132,
        "durationLabel": "02:12",
        "sizeBytes": 5287100,
        "sizeLabel": "5.0 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "02:12"
  },
  {
    "id": "6a58-6d32-82b1-706b",
    "title": "橘洲花火",
    "category": "demo",
    "publishedAt": "2024-07-30",
    "versions": [
      {
        "name": "橘洲花火_part1",
        "filename": "橘洲花火_part1.mp3",
        "modifiedAt": "2022-09-05",
        "audio": "https://audio.aimaradio.com/demo/%E6%A9%98%E6%B4%B2%E8%8A%B1%E7%81%AB_part1.mp3",
        "durationSeconds": 122,
        "durationLabel": "02:02",
        "sizeBytes": 4894219,
        "sizeLabel": "4.7 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "橘洲花火_pt2",
        "filename": "橘洲花火_pt2.mp3",
        "modifiedAt": "2022-12-18",
        "audio": "https://audio.aimaradio.com/demo/%E6%A9%98%E6%B4%B2%E8%8A%B1%E7%81%AB_pt2.mp3",
        "durationSeconds": 159,
        "durationLabel": "02:39",
        "sizeBytes": 6377974,
        "sizeLabel": "6.1 MB",
        "bitrateKbps": 320,
        "tags": {}
      },
      {
        "name": "橘洲花火_pt3",
        "filename": "橘洲花火_pt3.mp3",
        "modifiedAt": "2024-07-30",
        "audio": "https://audio.aimaradio.com/demo/%E6%A9%98%E6%B4%B2%E8%8A%B1%E7%81%AB_pt3.mp3",
        "durationSeconds": 244,
        "durationLabel": "04:04",
        "sizeBytes": 9781207,
        "sizeLabel": "9.3 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "04:04"
  },
  {
    "id": "6708-304b-3099-7dba-9e97-3066-3099-3059-306d",
    "title": "月が綺麗ですね",
    "category": "demo",
    "publishedAt": "2024-01-20",
    "versions": [
      {
        "name": "月が綺麗ですね",
        "filename": "月が綺麗ですね.mp3",
        "modifiedAt": "2024-01-20",
        "audio": "https://audio.aimaradio.com/demo/%E6%9C%88%E3%81%8B%E3%82%99%E7%B6%BA%E9%BA%97%E3%81%A6%E3%82%99%E3%81%99%E3%81%AD.mp3",
        "durationSeconds": 252,
        "durationLabel": "04:12",
        "sizeBytes": 10071688,
        "sizeLabel": "9.6 MB",
        "bitrateKbps": 320,
        "tags": {}
      }
    ],
    "durationLabel": "04:12"
  },
  {
    "id": "yali-jazz",
    "title": "yali_jazz",
    "category": "demo",
    "publishedAt": "2022-03-23",
    "versions": [
      {
        "name": "yali_jazz",
        "filename": "yali_jazz.mp3",
        "modifiedAt": "2022-03-23",
        "audio": "https://audio.aimaradio.com/demo/yali_jazz.mp3",
        "durationSeconds": 81,
        "durationLabel": "01:21",
        "sizeBytes": 1625255,
        "sizeLabel": "1.5 MB",
        "bitrateKbps": 160,
        "tags": {}
      }
    ],
    "durationLabel": "01:21"
  },
  {
    "id": "1-1",
    "title": "1.1",
    "category": "demo",
    "publishedAt": "2022-01-01",
    "versions": [
      {
        "name": "1.1",
        "filename": "1.1.mp3",
        "modifiedAt": "2022-01-01",
        "audio": "https://audio.aimaradio.com/demo/1.1.mp3",
        "durationSeconds": 135,
        "durationLabel": "02:15",
        "sizeBytes": 2700978,
        "sizeLabel": "2.6 MB",
        "bitrateKbps": 160,
        "tags": {}
      }
    ],
    "durationLabel": "02:15"
  },
  {
    "id": "3c3",
    "title": "σ",
    "category": "demo",
    "publishedAt": "2021-11-25",
    "versions": [
      {
        "name": "σ",
        "filename": "σ.mp3",
        "modifiedAt": "2021-11-20",
        "audio": "https://audio.aimaradio.com/demo/%CF%83.mp3",
        "durationSeconds": 446,
        "durationLabel": "07:26",
        "sizeBytes": 8933794,
        "sizeLabel": "8.5 MB",
        "bitrateKbps": 160,
        "tags": {}
      },
      {
        "name": "σ_雅礼蓝版",
        "filename": "σ_雅礼蓝版.mp3",
        "modifiedAt": "2021-11-25",
        "audio": "https://audio.aimaradio.com/demo/%CF%83_%E9%9B%85%E7%A4%BC%E8%93%9D%E7%89%88.mp3",
        "durationSeconds": 41,
        "durationLabel": "00:41",
        "sizeBytes": 824341,
        "sizeLabel": "0.8 MB",
        "bitrateKbps": 161,
        "tags": {}
      }
    ],
    "durationLabel": "00:41"
  }
];
const tracks = [
  {
    "id": "3a9",
    "title": "Ω",
    "filename": "Ω.mp3",
    "category": "track",
    "publishedAt": "2023-01-01",
    "zh": {
      "note": "夜，拂晓，东云，日出，晴"
    },
    "en": {
      "note": "Night, daybreak, clouds in the east, sunrise, clear skies."
    },
    "photos": [
      {
        "src": "assets/content/track/3a9/01.jpg",
        "caption": "IMG_5509"
      }
    ],
    "cover": "assets/content/track/3a9/01.jpg",
    "audio": "https://audio.aimaradio.com/track/%CE%A9.mp3",
    "durationSeconds": 155,
    "durationLabel": "02:35",
    "sizeBytes": 6185713,
    "sizeLabel": "5.9 MB",
    "bitrateKbps": 320,
    "tags": {}
  },
  {
    "id": "obeta",
    "title": "Oβ",
    "filename": "Oβ.mp3",
    "category": "track",
    "publishedAt": "2022-04-30",
    "zh": {
      "note": "清晨虚无月夜，湖木飘落森森"
    },
    "en": {
      "note": "Morning emptiness under a moonlit night, leaves drifting across the wooded lake."
    },
    "photos": [
      {
        "src": "assets/content/track/obeta/01.jpg",
        "caption": "cover"
      }
    ],
    "cover": "assets/content/track/obeta/01.jpg",
    "audio": "https://audio.aimaradio.com/track/O%CE%B2.mp3",
    "durationSeconds": 530,
    "durationLabel": "08:50",
    "sizeBytes": 21186268,
    "sizeLabel": "20.2 MB",
    "bitrateKbps": 320,
    "tags": {}
  }
];
const notes = [
  {
    "id": "4e66-8bc4-20-54c1-9274-300a-65e0-4eba-901d-53bb-300b",
    "category": "note",
    "publishedAt": "2025-11-14",
    "zh": {
      "title": "品鉴《无人逝去》",
      "heading": "因为经常要靠听说书才能入睡\n不知不觉听了很多推理小说\n心血来潮就开始看一些推理小说了",
      "body": [
        "从此作开始正式入坑白井了",
        "五重反转 全员推理\n纯粹的 极高密度的伏线与逻辑推理\n从第一页开始提到的所有细节全都是伏线 平均十页一个推理\n没有社会派那些人性探讨 甚至也很少有人物和人物关系的塑造\n人物 设定 情节 包括动机\n一切都是为了诡计和推理服务",
        "真的太流畅 太爽了",
        "这就是设定系逻辑流吗\n这就是新本格吗\n这就是 白井智之 吗（仰望"
      ],
      "date": "2025.11.14"
    },
    "en": {
      "title": "Reading No One Died",
      "heading": "Book notes",
      "body": [
        "I often need an audiobook to fall asleep, and without noticing it I had listened to a great many mystery novels. On a whim, I finally started reading some mysteries for myself.",
        "This was the book that properly pulled me into Tomoyuki Shirai.",
        "Five reversals. Everyone reasons. It is pure, extremely dense foreshadowing and deduction. Every detail mentioned from the first page turns out to be a clue; there is practically a new piece of reasoning every ten pages. There is none of the social school’s examination of human nature, and barely any conventional shaping of characters or relationships. Character, setting, plot, even motive—everything exists to serve the trick and the deduction.",
        "It is unbelievably smooth. Unbelievably satisfying.",
        "So this is logic driven by an invented premise? This is the new orthodox? This is Tomoyuki Shirai? (looks upward)"
      ],
      "date": "14 Nov 2025"
    },
    "photos": [
      {
        "src": "assets/content/note/4e66-8bc4-20-54c1-9274-300a-65e0-4eba-901d-53bb-300b/01.jpg",
        "caption": "无人逝去1"
      },
      {
        "src": "assets/content/note/4e66-8bc4-20-54c1-9274-300a-65e0-4eba-901d-53bb-300b/02.jpg",
        "caption": "无人逝去2"
      }
    ],
    "cover": "assets/content/note/4e66-8bc4-20-54c1-9274-300a-65e0-4eba-901d-53bb-300b/01.jpg"
  }
];
const siteAudio = {
  "src": "https://audio.aimaradio.com/radio/20250731%20-%20Oboro.mp3",
  "volume": 1,
  "label": "20250731 - Oboro",
  "href": "#episode/oboro"
};
